# version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: cv_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: control_visitas
      MYSQL_TCP_PORT: 3306
    ports:
      - "3307:3306" # expuesto en tu host (evita choque con MySQL local)
    volumes:
      - db_data:/var/lib/mysql
    command:
      [
        "--default-authentication-plugin=mysql_native_password",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]

  adminer:
    image: adminer
    container_name: cv_adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

  api:
    build: ./backend
    container_name: cv_api
    working_dir: /app
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: sh -lc "npm install && npm run start:dev"

  web:
    build: ./frontend
    container_name: cv_web
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "4200:4200"
    command: sh -lc "npm install && ng serve --host 0.0.0.0 --port 4200 --poll 2000"
    depends_on:
      - api

volumes:
  db_data:
